"""add assignment outcome

Revision ID: 1aef5e030f06
Revises: e79d14801b95
Create Date: 2026-09-06 21:32:29.167630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aef5e030f06'
down_revision: Union[str, None] = 'e79d14801b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_assignments', sa.Column('outcome', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_assignments', 'outcome')
    # ### end Alembic commands ###
